.\" Process this file with
.\" groff -man -Tascii stepmania.6
.\"
.TH stepmania 6 "JUNE 2019" Linux "User Manuals"
.SH NAME
stepmnania \- Advanced cross-platform rhythm game for home and arcade use
.SH SYNOPSIS
.B stepmania
.SH DESCRIPTION
.B stepmania
This package was specifically built for the Raspberry Pi platform.
For more information about the process used to create this package,
visit https://github.com/SpottyMatt/raspbian-stepmania-deb

There is much more that must be configured on a Raspberry Pi to
make StepMania playable. For more information, instructions,
& a set of scripts to do it all automatically, visit
https://github.com/SpottyMatt/raspbian-3b-stepmania-arcade
.SH AUTHOR
Packaged by Matthias Rozensztok <SpottyMatt@gmail.com>

